CMU-313/CMU-313.github.io

assignments/hw6.md
I have left the other parts as comments - hopefully students won't be ambitious enough to dig forward.
=> Added HW6 Deliverable A

recitations/reci7-machine-learning.md, schedule.md
updated schedule to add handout and slides, uses codespaces for setup
=> adding recitation 7 machine learning

docs/index.md
Updates calendar to [S23 version](https://calendar.google.com/calendar/embed?src=c_1103eea63731dc779de16d03b476d0d9b7cf18f05132c28332628299ea064258%40group.calendar.google.com&ctz=America%2FNew_York)
=> Updates calendar for S23

docs/syllabus.md
Updates syllabus based on proposed changes
=> Updates syllabus S23

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci1-github.md, mkdocs.yml
Adds [handout](https://docs.google.com/document/d/1Cxl6L3SZ4tLXxC3Wvu1crE1Z6gZKng5OIke4zbjdiTw/edit#)
=> Adds recitation 1

docs/_data/schedule.yaml, docs/_data/this_week.yaml, mkdocs.yml
=> show rec 3

docs/projects/P2/2_firstsprint.md, mkdocs.yml, overrides/main.html
- Use MkDocs announcement feature to create announcements
- Allows for dismissing of announcement
- Add clarification on "What if I did not successfully translate my file in Project 1?"
=> Adds p2 announcement and clarification

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci4-dysfunction.md, mkdocs.yml
=> Adds Recitation 4

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci6-deployment.md, mkdocs.yml
Adds recitation 6 handout and updates schedule. Recitation 6 covers deployment and guides students through setting up the basic-web-app with Fly.io and creating GH actions.
=> Add recitation 6 - deployment

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/projects/P3/index.md
Changes final deliverable for P3 from Tuesday to Thursday
=> Update schedule for Final Deliverable

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci9-ml.md, mkdocs.yml
Adds slides, handout, and gradescope quiz to the website 
Updates schedule and this week pages
=> Adds recitation 9 machine learning content

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci11-p5-checkin.md, mkdocs.yml
Handout links to feedback form
=> Add recitation 11 - P5 checkpoint presentation content

docs/syllabus.md
Based on ongoing discussions with @abegel.
=> Update policies for Fall 2023

docs/index.md
Embedding a Google calendar for lecture timings and office hours
=> Class calendar

.github/workflows/deploy.yml, .github/workflows/update.yml, docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/index.md, docs/recitations/reci1-github.md, docs/syllabus.md, mkdocs.yml
Recitation 1 for F23 based on [handout](https://docs.google.com/document/d/1lPk7Q1ksDagqxUFo2TufCDAYPS_-HofL03N8R5cnweU/edit)
=> Adds recitation 1 - Git, GitHub and TypeScript

docs/_data/schedule.yaml
Placeholder dates for all projects and links to P1. Includes a minor fix to recitation slot on schedule.
=> Schedule: projects

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci2-teamcontract.md, mkdocs.yml
Added Recitation 2 links and handout to site. Looked normal on localhost but please verify that the gradescope link goes to the correct place since it redirects me to submissions when I try to test it. Thanks!
=> Adding recitation 2

docs/_data/schedule.yaml, docs/projects/P2/1_teamprocess.md, docs/projects/P2/2_firstsprint.md, docs/projects/P2/3_secondsprint.md, docs/projects/P2/index.md, mkdocs.yml
=> Adds P2 handout

docs/_data/schedule.yaml, docs/recitations/reci8-llms.md
=> Adds Recitation 8

docs/_data/schedule.yaml, mkdocs.yml
Fixes schedule issue for Recitation 8 and updates due date for P4 to Nov 21.
=> Fix schedule for Recitation 8

docs/_data/schedule.yaml, docs/projects/P4/index.md, mkdocs.yml
From [gdoc here](https://docs.google.com/document/d/1J5Tqij0o8IDlAuy2LlqvLnLsKh9X9fP4AbD0qwKND0U/edit#heading=h.61j3jb1hctog)
=> Adds P4 handout

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci10-team-feedback.md, mkdocs.yml
Add team feedback recitation to site and updates schedule
=> Adds team feedback recitation

docs/_data/schedule.yaml, docs/projects/P5/1_projectcheck.md, docs/projects/P5/2_projectfinal.md, docs/projects/P5/index.md, mkdocs.yml
=> Adds P5 Handout

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci11-p5-checkin.md, mkdocs.yml
Adds P5 checin presentation recitation and updates schedules
=> adds recitation 11 and updates website

docs/_data/schedule.yaml, docs/_data/this_week.yaml
Updates yaml files with recitation 12 + gradescope quiz
=> Updates schedule with recitation 12

docs/_data/schedule.yaml, docs/_data/this_week.yaml
=> updates schedule with room for final presentations

mkdocs.yml
Updates canvas and gradescope link
=> Updates canvas link

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci1-github.md, mkdocs.yml
Updated recitation handout, navigation bar, and schedule to include the first recitation of the semester. All links work as expected in the deployment preview.
=> Adding reci1 to site

docs/_data/schedule.yaml
Adds lecture names for semester to schedule
=> Updates Schedule

docs/_data/schedule.yaml, docs/projects/P2/1_teamprocess.md, docs/projects/P2/2_firstsprint.md, docs/projects/P2/3_secondsprint.md, docs/projects/P2/index.md, mkdocs.yml
As title says, Added P2 to all parts of the course website, including the schedule and updated the dates in the writeup to line up with semester schedule.
=> Added P2 to course website

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci5-team-dysfunction.md, mkdocs.yml
1. Created recitation handout instructions (`docs/recitations/reci5-team-dysfunction.md`)
2. Added the handout to be released on the course website (`docs/_data/schedule.yaml`)
3. Added the handout to be released on this week's schedule (`docs/_data/this_week.yaml`)
4. Added the handout into the build (`mkdocs.yml`)
=> Create materials for Recitation 5 - Team Dysfunction

docs/recitations/reci5-team-dysfunction.md
1. Changed the markdown file to update instructions for Recitation 5 to be a skit rather than a group activity.
=> Change Recitation 5 to be a skit rather than a group activity

docs/_data/schedule.yaml, docs/recitations/reci7-llms.md, mkdocs.yml
Adds LLM recitation with:
- updated recitation number and links 
- cleaned up and updated language in some spots
=> Adds Recitation 7 Large Language Models

docs/_data/schedule.yaml, docs/projects/P4/index.md
This branch updates P4. Major changes: tasks changed to language translation
=> P4 S24 updates 

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci8-team-feedback.md, mkdocs.yml
This change adds Recitation 8 (3/25) Team Feedback by publishing the actual recitation and updating the website links.
=> Add Recitation 8 Team Feedback 

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/projects/P4/index.md, mkdocs.yml
=> Updating P4 Deadline + Adding P4 to Project List

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci9-open-source.md, mkdocs.yml
Adds Recitation 9 (4/1) "Open Source Scavenger Hunt" by updating links and slides.
=> Add Recitation 9 - Open Source Scavenger Hunt

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci11-midterm-review.md, mkdocs.yml
Adding new midterm review recitation to website
=> Adding Recitation 11

docs/_data/schedule.yaml, docs/projects/P2/1_teamprocess.md, docs/projects/P2/2_firstsprint.md, docs/projects/P2/3_secondsprint.md, docs/projects/P2/index.md, mkdocs.yml
Adding updated information to website for project 2
=> updating project 2 data for F24

docs/projects/P2/1_teamprocess.md, docs/projects/P2/2_firstsprint.md
removing references to typescript assignment in P2B and adding description of creating project boards to P2A
=> removing references to typescript assignment 

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci4-checkpoint.md, mkdocs.yml
Second pull request as first one had isues with loading the handout link/file
=> Reci4 f24 fixed issues with loading handout

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci5-team-dysfunction.md, mkdocs.yml
Created recitation handout instructions (docs/recitations/reci5-team-dysfunction.md)
Added the handout to be released on the course website (docs/_data/schedule.yaml)
Added the handout to be released on this week's schedule (docs/_data/this_week.yaml)
Added the handout into the build (mkdocs.yml)
=> Add Recitation 5 Team Dysfunction 

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci6-deployment.md, mkdocs.yml
Changed this_week, schedule.yml files and the recitation 6 handout.
=> Made changes to add recitation 6 documents and handout on website

docs/_data/schedule.yaml, docs/recitations/reci7-azure-setup.md, mkdocs.yml
Edited necessary files for Recitation 7 - Azure Setup in preparation for P3 Build using Azure for Fall 2024 Instance of the class
=> Recitation 7 Azure Setup Fall 2024

docs/projects/P3/index.md
Updated public spreadsheet links for P3 from S24 version to F24 version
=> P3 - Update public spreadsheet links

docs/_data/staff.yaml
=> Update staff.yaml to Add TA Lara's Photo

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci8-llms.md, mkdocs.yml
Created recitation handout instructions (docs/recitations/reci8-team-dysfunction.md)
Added the handout to be released on the course website (docs/_data/schedule.yaml)
Added the handout to be released on this week's schedule (docs/_data/this_week.yaml)
Added the handout into the build (mkdocs.yml)
=> add material for recitation 8

docs/_data/schedule.yaml, docs/recitations/reci9-team-feedback.md, mkdocs.yml
Added .md file with recitation 9 overview and instructions to _data/recitations. Also updated mkdocs.yml and schedule.yaml adding recitation 9 information
=> Adding Recitation 9  information to website

docs/_data/schedule.yaml, docs/projects/P4/index.md, mkdocs.yml
Updated the P4 document to include the new information about the project
1. Added new restriction on Azure credits
2. Removed “2. Integrate a Python-based serverless function” in Checkpoint 1
3.  The new colab notebook is finished, I just need to create a blank (i.e. non-solution version) to add the link for
4. Fixed due dates (are these correct? I made a guess, so I want to bring extra attention to them)
=> update P4 doc

docs/_data/schedule.yaml, docs/_data/this_week.yaml
=> fix due dates

docs/_data/schedule.yaml, docs/_data/this_week.yaml, mkdocs.yml
Modified `mkdocs.yml`, `schedule.yml`, `this_week.yml` to include recitation 10. Kept the assignment the same as last year
=> Recitation 10 - Open Source

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci2-teamcontract.md, mkdocs.yml
Modified schedule and updated links for S25
=> Added Reci2

docs/_data/schedule.yaml, docs/_data/this_week.yaml, mkdocs.yml
made updates/linked reci 3 material.
=> Recitation 3 Spring 2025 Updated Websites to link handouts, quiz and other links

docs/_data/schedule.yaml, docs/index.md
Edited schedule.yaml.
Adding Google Drive link to Midterm lecture so students can access review materials
=> Adding link to Previous Midterms to Schedule

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci8-llms.md, mkdocs.yml
Updates to the schedule and this week for reci 8.
=> Recitation 8 - update to 2025

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/projects/P4/index.md, mkdocs.yml
- Update schedule and this week for P4
- Switch from Azure to OpenAI API
=> Updating P4 to not use azure

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/projects/P4/index.md
=> Update dates for P4

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci9-open-source.md, mkdocs.yml
- Changed links to spreadsheets, slides, and gradescope
- Changed dates and schedule
=> Recitation 9

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci10-team-feedback.md, mkdocs.yml
updated reci10-team-feedback based on checklist
=> updated reci10-team-feeback based on checklist

docs/projects/P1/development-tools-guide.md, docs/projects/P1/git-commands-reference.md, mkdocs.yml
This PR adds comprehensive educational resources to Project 1 that explain the fundamental tools and concepts students encounter during setup.
- **Development Tools Guide**: `docs/projects/P1/development-tools-guide.md`
- **Git Commands Reference**: `docs/projects/P1/git-commands-reference.md`
- **Navigation updates**: Added both guides to Project 1 section in `mkdocs.yml`
Many students struggle with P1 setup because they don't understand the **why** behind the tools. This creates confusion and makes debugging difficult.
**Reduced Setup Time**: Students understand what they're doing
**Better Debugging**: Understanding tools helps students solve problems  
**Foundation for Success**: Concepts apply throughout the course
Would love to get this added to help current and future students!
What …
=> Add Development Tools Guide + Specific Git Commands for Project 1 

docs/_data/schedule.yaml, docs/_data/this_week.yaml, docs/recitations/reci3-archaeology-ta-guide.md, docs/recitations/reci3-archaeology.md, mkdocs.yml
• Set up Recitation 3 - Software Archaeology with all required components
• Updated navigation, schedule data, and current week information  
• Created comprehensive TA guide for running the recitation effectively
• Tested preview to ensure all links work correctly
- **Slides**: https://docs.google.com/presentation/d/19ym2ZT1t6W4942ayiTozBwoFtsEOPANeRBH1UB7g9k4/edit?usp=sharing
- **Gradescope Quiz**: https://www.gradescope.com/courses/1086939/assignments/6689436/
- **GitHub Repository**: https://github.com/CMU-313/NodeBB
=> Set up Recitation 3 - Software Archaeology

docs/_data/schedule.yaml, docs/projects/P2/2_firstsprint.md, docs/recitations/reci4-checkpoint.md, mkdocs.yml
**Recitation Page**
**Schedule:**
=> Make recitation 4 go live

docs/_data/schedule.yaml, docs/recitations/reci6-deployment.md, mkdocs.yml
Updated Fall 2025 website with recitation 6.
=> Updated website with reci 6, Fall 2025
